# 应用服务 WEB 访问端口
server:
  port: 8108
#  servlet:
#    context-path: /api
spring:
  application:
    name: take-out-file
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public
# 阿里云对象云存储配置
aliyun:
  oss: #存储
    file:
      endpoint: oss-cn-beijing.aliyuncs.com   # 域
      accessKeyId: LTAI5tDn3tjPzSEHfSSCAh1b  # 秘钥KeyId
      accessKeySecret: svQugzLMYOEsrnCom47Xy9uXeEeVUF # 秘钥KeySecret
      bucketName: take-out-file  # 桶名
      url: https://take-out-file.oss-cn-beijing.aliyuncs.com  # 访问地址
sky:
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDn3tjPzSEHfSSCAh1b
    access-key-secret: svQugzLMYOEsrnCom47Xy9uXeEeVUF
    bucket-name: take-out-file